# Generated by Django 6.0 on 2025-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_submitted_at_enquiry_date_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='job_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
