# Generated by Django 6.0 on 2025-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_enquiry_company_name_alter_enquiry_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='job_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
