# Generated by Django 6.0 on 2025-12-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
