# Generated by Django 6.0 on 2025-12-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at']},
        ),
    ]
