"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gox5w@2&t29j9o=u=4#be*s0l@_$qc&_vwac4&^bvd3q3on2ov'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

ADMIN_SITE_HEADER = "AI-Solutions Administration"
ADMIN_SITE_TITLE = "AI-Solutions Admin"
ADMIN_INDEX_TITLE = "Welcome to AI-Solutions Admin Dashboard"

AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ✅ IMPORTANT
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


JAZZMIN_SETTINGS = {
    "show_ui_builder": False,
    "site_title": "AI-Solutions Admin",
    "site_header": "AI-Solutions",
    "site_brand": "AI-Solutions",
    "login_logo": None,


    # 🔹 Login page title
    "welcome_sign": "Welcome to AI-Solutions Admin",

    # 🔹 Top navbar links
    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": False},
        {"name": "View Website", "url": "/", "new_window": True},
    ],

    # 🔹 Sidebar menu
    "show_sidebar": True,
    "navigation_expanded": True,

    # 🔹 UI Theme (AI-friendly)
    "theme": "darkly",
    "dark_mode_theme": "darkly",

    # 🔹 Accent colors
    "accent": "primary",
    "navbar": "dark",
    "sidebar": "dark",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-light",
    },

    # 🔹 Custom model names
    
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # clean & professional
    "dark_mode_theme": "darkly",

    "navbar": "navbar-dark bg-primary",
    "sidebar": "sidebar-dark-primary",

    "accent": "accent-primary",
    "brand_colour": "navbar-primary",

    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "success": "btn-success",
        "danger": "btn-danger",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

import os
from pathlib import Path

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
